engine:  
  type: "in_memory"
network:  
  address: "127.0.0.1:3223"  
  max_connections: 10  
  idle_timeout: 5m
  max_message_size: "4KB"
logging:  
  level: "local"  
  output: "/log/output.log"
wal:  
  flushing_batch_size: 100
  flushing_batch_timeout: "10ms"
  max_segment_size: "10MB"
  data_directory: "/data/venom/wal"